pipeline:
  identifier: Build_hergi2004_helloworld_1719892337160
  name: Build helloworld
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1719892228062
        repoName: hergi2004/helloworld
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    caching: true
                    connectorRef: <+input>
                    repo: hello/world
                    tags:
                      - latest
                  timeout: ""
                  type: BuildAndPushDockerRegistry
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_2
                  identifier: BuildAndPushDockerRegistry_2
                  spec:
                    connectorRef: account.harnessImage
                    repo: hergi2004/helloworld
                    tags:
                      - latest
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
